@host = http://localhost:5242

### 1. Összes eszköz lekérése
GET {{host}}/api/szavazo
Content-Type: application/json
{
  "nev": "Szabó Bence"
}
###

### 3. Eszköz módosítása
PUT {{host}}/api/szavazo/1
Content-Type: application/json

{
  "nev": "Szabó Bence",
  "osztaly": "9.B",
  "szavazott": "1",
  "kireSzavazott": "Huawei"
}

###