@host = http://localhost:5242

### 1. Összes eszköz lekérése
GET {{host}}/api/szavazok

###

### 3. Eszköz módosítása
PUT {{host}}/api/szavazok/1
Content-Type: application/json

{
  "nev": "Módosított tanári laptop",
  "leltariSzam": "IT-001",
  "kategoria": "Laptop",
  "gyarto": "Dell",
  "modell": "Latitude 5420",
  "terem": "A315",
  "allapot": "Jó",
  "hasznalatbanVan": true,
  "kolcsonozheto": true,
  "beszerzesiAr": 280000,
  "beszerzesDatuma": "2022-09-01"
}

###