CREATE DATABASE `szavazok` /*!40100 COLLATE 'utf8mb4_uca1400_ai_ci' */;

CREATE TABLE `szavazok` (
	`nev` VARCHAR(100) NULL DEFAULT NULL COLLATE 'utf8mb4_uca1400_ai_ci',
	`osztaly` VARCHAR(10) NULL DEFAULT NULL COLLATE 'utf8mb4_uca1400_ai_ci',
	`szavazott` TINYINT(1) NOT NULL,
	`kireSzavazott` VARCHAR(50) NULL DEFAULT NULL COLLATE 'utf8mb4_uca1400_ai_ci'
)
COLLATE='utf8mb4_uca1400_ai_ci'
ENGINE=InnoDB
;

INSERT INTO szavazok (nev, osztaly, szavazott, kireSzavazott) VALUES
('Kovács Péter', '9.A', 1, 'Apple'),
('Nagy Anna', '9.A', 1, 'Samsung'),
('Szabó Bence', '9.B', 0, NULL),
('Tóth Réka', '9.B', 1, 'Xiaomi'),
('Varga Dániel', '9.C', 1, 'Huawei'),
('Kiss Zsófia', '9.C', 0, NULL),
('Molnár Máté', '10.A', 1, 'Apple'),
('Németh Eszter', '10.A', 1, 'Samsung'),
('Farkas Balázs', '10.B', 1, 'Xiaomi'),
('Balogh Dóra', '10.B', 0, NULL),
('Takács Gergő', '10.C', 1, 'Huawei'),
('Juhász Lili', '10.C', 1, 'Apple'),
('Lakatos Ádám', '11.A', 0, NULL),
('Mészáros Flóra', '11.A', 1, 'Samsung'),
('Oláh Dávid', '11.B', 1, 'Xiaomi'),
('Simon Boglárka', '11.B', 1, 'Huawei'),
('Rácz Tamás', '11.C', 0, NULL),
('Fekete Csilla', '11.C', 1, 'Apple'),
('Szilágyi Kristóf', '12.A', 1, 'Samsung'),
('Török Laura', '12.A', 0, NULL),
('Fehér Márk', '12.B', 1, 'Xiaomi'),
('Gál Vivien', '12.B', 1, 'Huawei'),
('Orsós Patrik', '12.C', 1, 'Apple'),
('Gulyás Noémi', '12.C', 0, NULL),
('Bíró Bence', '9.A', 1, 'Samsung'),
('Kerekes Luca', '9.A', 1, 'Xiaomi'),
('Horváth Áron', '9.B', 0, NULL),
('Major Hanna', '9.B', 1, 'Huawei'),
('Szücs Zoltán', '9.C', 1, 'Apple'),
('Pintér Dorina', '9.C', 0, NULL),
('Deák Botond', '10.A', 1, 'Samsung'),
('László Fanni', '10.A', 1, 'Xiaomi'),
('Kovács Krisztián', '10.B', 0, NULL),
('Nagy Bianka', '10.B', 1, 'Huawei'),
('Szabó Levente', '10.C', 1, 'Apple'),
('Tóth Kitti', '10.C', 0, NULL),
('Varga Milán', '11.A', 1, 'Samsung'),
('Kiss Barbara', '11.A', 1, 'Xiaomi'),
('Molnár Dominik', '11.B', 0, NULL),
('Németh Gréta', '11.B', 1, 'Huawei'),
('Farkas Marcell', '11.C', 1, 'Apple'),
('Balogh Emma', '11.C', 0, NULL),
('Takács Attila', '12.A', 1, 'Samsung'),
('Juhász Sára', '12.A', 1, 'Xiaomi'),
('Lakatos Norbert', '12.B', 0, NULL),
('Mészáros Blanka', '12.B', 1, 'Huawei'),
('Oláh Bálint', '12.C', 1, 'Apple'),
('Simon Jázmin', '12.C', 0, NULL),
('Rácz Roland', '9.A', 1, 'Samsung'),
('Fekete Viktória', '9.A', 1, 'Xiaomi'),
('Szilágyi Oliver', '9.B', 0, NULL),
('Török Léna', '9.B', 1, 'Huawei'),
('Fehér Kornél', '9.C', 1, 'Apple'),
('Gál Lilla', '9.C', 0, NULL),
('Orsós Richárd', '10.A', 1, 'Samsung'),
('Gulyás Zoé', '10.A', 1, 'Xiaomi'),
('Bíró Alex', '10.B', 0, NULL),
('Kerekes Kamilla', '10.B', 1, 'Huawei'),
('Horváth Barnabás', '10.C', 1, 'Apple'),
('Major Panna', '10.C', 0, NULL),
('Szücs Noel', '11.A', 1, 'Samsung'),
('Pintér Bella', '11.A', 1, 'Xiaomi'),
('Deák Máté', '11.B', 0, NULL),
('László Lotti', '11.B', 1, 'Huawei'),
('Kovács Zsombor', '11.C', 1, 'Apple'),
('Nagy Anna', '11.C', 0, NULL),
('Szabó Dániel', '12.A', 1, 'Samsung'),
('Tóth Natália', '12.A', 1, 'Xiaomi'),
('Varga Viktor', '12.B', 0, NULL),
('Kiss Bíborka', '12.B', 1, 'Huawei'),
('Molnár Zalán', '12.C', 1, 'Apple'),
('Németh Mira', '12.C', 0, NULL),
('Farkas Benedek', '9.A', 1, 'Samsung'),
('Balogh Maja', '9.A', 1, 'Xiaomi'),
('Takács Dávid', '9.B', 0, NULL),
('Juhász Liliána', '9.B', 1, 'Huawei'),
('Lakatos Hunor', '9.C', 1, 'Apple'),
('Mészáros Lara', '9.C', 0, NULL),
('Oláh Ádám', '10.A', 1, 'Samsung'),
('Simon Szonja', '10.A', 1, 'Xiaomi'),
('Rácz Erik', '10.B', 0, NULL),
('Fekete Izabella', '10.B', 1, 'Huawei'),
('Szilágyi Dániel', '10.C', 1, 'Apple'),
('Török Hanna', '10.C', 0, NULL),
('Fehér Csaba', '11.A', 1, 'Samsung'),
('Gál Eliza', '11.A', 1, 'Xiaomi'),
('Orsós Kevin', '11.B', 0, NULL),
('Gulyás Adél', '11.B', 1, 'Huawei'),
('Bíró Kristóf', '11.C', 1, 'Apple'),
('Kerekes Rozi', '11.C', 0, NULL),
('Horváth Milán', '12.A', 1, 'Samsung'),
('Major Laura', '12.A', 1, 'Xiaomi'),
('Szücs Ákos', '12.B', 0, NULL),
('Pintér Emma', '12.B', 1, 'Huawei'),
('Deák Bence', '12.C', 1, 'Apple'),
('László Zsófia', '12.C', 0, NULL),
('Kovács Patrik', '9.A', 1, 'Samsung'),
('Nagy Dorottya', '9.B', 1, 'Xiaomi'),
('Szabó Vince', '9.C', 0, NULL),
('Tóth Rebeka', '10.A', 1, 'Huawei');